# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815caa748d636b795c9d2c655e095020dedf03aaec018bbb25bfa27060e67f57946b106c677db175a97530496e738984c9c70e41a8a233bf0b02f3a70a4c1023

test:
  secret_key_base: 8a0617ea80307a785dfa40a3f3c6c65eaf79489e4bef67184c880f445459a253650e1517feec80ba088f7c4d6f1a8653c9f4db680f81705b40f0d5d0bbec4478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
